### ISSUE TITLE
Switch to Mbps?

### ISSUE THREAD

**Issue by inadarei** [xxczaki/speedo-cli#1]
This is very nice tool! Thanks for creating it.

Currently it reports speed in kilobytes, but usually internet speed is reported in megabits per second (Mbps). That is what fast.com, speedtest.com do and that is also how providers market their speed.

Maybe it is better to convert speedo's reporting to mbps, as well?

**Comment by xxczaki** [comment]
Yeah, I was thinking about that :smile:

**Comment by xxczaki** [comment]
@inadarei Done, however I changed kB/s not to Mb/s, but to MB/s .
